### ISSUE TITLE
Create Github bot potogold

### ISSUE THREAD

**Issue by netbe** [netbe/potogold#2]
- [x] read up on best practices for creating bots
- [x] create account
- [x] save credentials in a local file (do not push on repo)
- [x] work out how to post comments
- [ ] work out how to receive push notifications

**Comment by potogold** [comment]
potogold!!

**Comment by potogold** [comment]
potogold!!

**Comment by potogold** [comment]
blah!

**Comment by benjaminwilson** [comment]
@potogold you are a weapon

**Comment by benjaminwilson** [comment]
@potogold wat up

**Comment by potogold** [comment]
@benjaminwilson wat up yaself

**Comment by benjaminwilson** [comment]
@potogold do something

**Comment by benjaminwilson** [comment]
@potogold why you ignore me

**Comment by benjaminwilson** [comment]
@potogold cut it out

**Comment by potogold** [comment]
yoyo

**Comment by potogold** [comment]
yoyo

**Comment by benjaminwilson** [comment]
@potogold add $200.

**Comment by potogold** [comment]
@benjaminwilson offers $200.000000

**Comment by benjaminwilson** [comment]
@potogold add $200.

**Comment by potogold** [comment]
@benjaminwilson offers $200.000000

**Comment by benjaminwilson** [comment]
potogold add $200.

**Comment by benjaminwilson** [comment]
@potogold add $200.

**Comment by potogold** [comment]
@benjaminwilson offers $200.00

**Comment by potogold** [comment]
@benjaminwilson offers $200.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe.

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by benjaminwilson** [comment]
@potogold hey there

**Comment by benjaminwilson** [comment]
@potogold it's gettin glate

**Comment by benjaminwilson** [comment]
@potogold add $300

**Comment by potogold** [comment]
@benjaminwilson I don't understand

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by benjaminwilson** [comment]
@potogold add $300.

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by benjaminwilson** [comment]
@potogold add $300

**Comment by potogold** [comment]
@benjaminwilson I don't understand

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by benjaminwilson** [comment]
@potogold add $500

**Comment by potogold** [comment]
@benjaminwilson offers $500.00

**Comment by benjaminwilson** [comment]
@potogold add $10000000

**Comment by potogold** [comment]
@benjaminwilson offers $10000000.00

**Comment by benjaminwilson** [comment]
@potogold wat up

**Comment by potogold** [comment]
@benjaminwilson I don't understand

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by benjaminwilson** [comment]
@potogold wat up

**Comment by potogold** [comment]
@benjaminwilson I don't understand

**Comment by potogold** [comment]
@benjaminwilson offers $300.00
