### ISSUE TITLE
setup database

### ISSUE THREAD

**Issue by netbe** [netbe/potogold#8]
http://blog.y3xz.com/blog/2012/08/16/flask-and-postgresql-on-heroku

**Comment by benjaminwilson** [comment]
@potogold add $500

**Comment by potogold** [comment]
@benjaminwilson offers $500.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson I don't understand

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by benjaminwilson** [comment]
@potogold add $350

**Comment by potogold** [comment]
@benjaminwilson offers $500.00

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson offers $350.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by benjaminwilson** [comment]
@potogold add $10000000

**Comment by potogold** [comment]
@benjaminwilson offers $10000000.00

**Comment by benjaminwilson** [comment]
@potogold reward @tomcek112

**Comment by potogold** [comment]
@benjaminwilson released funds to @tomcek112

**Comment by potogold** [comment]
@benjaminwilson offers $500.00

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe
