### ISSUE TITLE
BIG FAT ISSUE

### ISSUE THREAD

**Issue by benjaminwilson** [netbe/potogold#9]
Something is very broken!

**Comment by benjaminwilson** [comment]
@potogold add $300

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by netbe** [comment]
@potogold add $300

**Comment by potogold** [comment]
@netbe offers $300.00

**Comment by netbe** [comment]
@potogold add $300

**Comment by potogold** [comment]
@netbe offers $300.00

**Comment by netbe** [comment]
@potogold add $450

**Comment by potogold** [comment]
@netbe offers $300.00

**Comment by benjaminwilson** [comment]
@potogold add $500000000

**Comment by potogold** [comment]
@netbe offers $300.00

**Comment by netbe** [comment]
@potogold add $300

**Comment by potogold** [comment]
@netbe offers $300.00

**Comment by netbe** [comment]
@potogold add $200

**Comment by potogold** [comment]
@netbe offers $200.00

**Comment by netbe** [comment]
@potogold add $200

**Comment by potogold** [comment]
@netbe offers $200.00

**Comment by netbe** [comment]
@potogold add $250

**Comment by potogold** [comment]
@netbe offers $250.00

**Comment by netbe** [comment]
@potogold reward @benjaminwilson

**Comment by potogold** [comment]
@netbe released funds to @benjaminwilson

**Comment by netbe** [comment]
@potogold reward @benjaminwilson

**Comment by potogold** [comment]
@netbe released funds to @benjaminwilson

**Comment by netbe** [comment]
@potogold reward @benjaminwilson

**Comment by potogold** [comment]
@netbe released funds to @benjaminwilson

**Comment by benjaminwilson** [comment]
@potogold add $222

**Comment by potogold** [comment]
@benjaminwilson offers $222.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by benjaminwilson** [comment]
@potogold add $215

**Comment by potogold** [comment]
@benjaminwilson offers $215.00

**Comment by benjaminwilson** [comment]
@potogold add $111

**Comment by potogold** [comment]
@benjaminwilson offers $111.00

**Comment by benjaminwilson** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson offers $222.00

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson offers $215.00

**Comment by potogold** [comment]
@benjaminwilson offers $111.00

**Comment by potogold** [comment]
@benjaminwilson released funds to @netbe

**Comment by netbe** [comment]
@potogold add $10

**Comment by potogold** [comment]
@netbe offers $10.00

**Comment by netbe** [comment]
@potogold reward @tomcek112

**Comment by potogold** [comment]
@netbe released funds to @tomcek112
